"""Contrastive / self-supervised model probers (CLIP ViT-B/32, DINOv2).

Both models are queried via zero-shot text-prompt similarity: we embed the
image and three text descriptions (correct, illusory, other) and return the
softmax over their cosine similarities as a ResponseDistribution.

The text descriptions are generated by ``src.probing.zero_shot.ZeroShotProtocol``.
"""

from __future__ import annotations

from typing import Any

import torch
import torch.nn.functional as F
from PIL import Image

from .base import ModelProber, ResponseDistribution


# ──────────────────────────────────────────────────────────────────────────────
# CLIP ViT-B/32  (via open-clip-torch)
# ──────────────────────────────────────────────────────────────────────────────

class CLIPProber(ModelProber):
    """CLIP ViT-B/32 zero-shot prober.

    Requires ``open-clip-torch`` (``pip install open-clip-torch``).
    Text prompts are injected at call time via the ``extra["text_prompts"]``
    dict with keys ``"correct"``, ``"illusory"``, ``"other"``.
    """

    model_name = "clip_vit_b32"

    def __init__(
        self,
        model_name: str = "ViT-B-32",
        pretrained: str = "openai",
        device: str | None = None,
    ) -> None:
        super().__init__(device)
        import open_clip  # type: ignore

        self._clip_model, _, self._preprocess = open_clip.create_model_and_transforms(
            model_name, pretrained=pretrained
        )
        self._clip_model = self._clip_model.to(self.device).eval()
        self._tokenize = open_clip.get_tokenizer(model_name)

    # ------------------------------------------------------------------
    @torch.no_grad()
    def _encode_image(self, image: Image.Image) -> torch.Tensor:
        x = self._preprocess(image).unsqueeze(0).to(self.device)
        feats = self._clip_model.encode_image(x)
        return F.normalize(feats, dim=-1)

    @torch.no_grad()
    def _encode_texts(self, prompts: list[str]) -> torch.Tensor:
        tokens = self._tokenize(prompts).to(self.device)
        feats = self._clip_model.encode_text(tokens)
        return F.normalize(feats, dim=-1)

    # ------------------------------------------------------------------
    def probe_pair(
        self,
        illusion: Image.Image,
        control: Image.Image,
        correct_answer: str,
        illusory_answer: str,
        category: str,
        illusion_type: str,
        extra: dict[str, Any] | None = None,
    ) -> ResponseDistribution:
        text_prompts = _get_text_prompts(extra, category, illusion_type)

        img_feat = self._encode_image(illusion)
        txt_feats = self._encode_texts(
            [text_prompts["correct"], text_prompts["illusory"], text_prompts["other"]]
        )

        logit_scale = self._clip_model.logit_scale.exp()
        logits = (logit_scale * img_feat @ txt_feats.T).squeeze(0)
        probs = torch.softmax(logits, dim=0).cpu().tolist()

        # Sanity: also score the control image
        ctrl_feat = self._encode_image(control)
        ctrl_logits = (logit_scale * ctrl_feat @ txt_feats.T).squeeze(0)
        ctrl_probs = torch.softmax(ctrl_logits, dim=0).cpu().tolist()

        # ctrl_argmax_correct=True means the control image is most confidently
        # "correct" — used by the argmax-based control ceiling in heas.py.
        ctrl_argmax_correct = int(ctrl_probs.index(max(ctrl_probs))) == 0

        return ResponseDistribution(
            correct=probs[0],
            illusory=probs[1],
            other=probs[2],
            raw={
                "logits": logits.cpu().tolist(),
                "probs_control": ctrl_probs,
                "ctrl_argmax_correct": ctrl_argmax_correct,
                "prompts": text_prompts,
            },
        )


# ──────────────────────────────────────────────────────────────────────────────
# DINOv2 (via HuggingFace transformers)
# ──────────────────────────────────────────────────────────────────────────────

class DINOv2Prober(ModelProber):
    """DINOv2 ViT-B/14 zero-shot prober.

    DINOv2 is a vision-only self-supervised model; we align image embeddings
    to text by using a lightweight text encoder.  For zero-shot scoring we
    use the CLIP text tower mapped into DINOv2 feature space via a stored
    linear projection, falling back to direct cosine similarity when no
    projection is available (the default during initial experiments).

    The simpler default: we embed the illusion image and three reference
    images (one per answer class) provided in ``extra["reference_images"]``,
    then compute cosine similarity.  This is the approach described by
    Caron et al. for retrieval evaluation.
    """

    model_name = "dinov2_vit_b14"

    def __init__(self, device: str | None = None) -> None:
        super().__init__(device)
        from transformers import AutoImageProcessor, AutoModel  # type: ignore

        self._processor = AutoImageProcessor.from_pretrained("facebook/dinov2-base")
        self._model = AutoModel.from_pretrained("facebook/dinov2-base").to(self.device).eval()

    @torch.no_grad()
    def _encode_image(self, image: Image.Image) -> torch.Tensor:
        inputs = self._processor(images=image, return_tensors="pt")
        inputs = {k: v.to(self.device) for k, v in inputs.items()}
        outputs = self._model(**inputs)
        # CLS token as the global representation
        feats = outputs.last_hidden_state[:, 0, :]
        return F.normalize(feats, dim=-1)

    def probe_pair(
        self,
        illusion: Image.Image,
        control: Image.Image,
        correct_answer: str,
        illusory_answer: str,
        category: str,
        illusion_type: str,
        extra: dict[str, Any] | None = None,
    ) -> ResponseDistribution:
        """Use reference image similarity for zero-shot scoring.

        ``extra`` must contain ``"reference_images"`` — a dict with keys
        ``"correct"``, ``"illusory"``, and ``"other"``, each a PIL Image
        representing a canonical exemplar of that answer class.  If absent,
        uniform scores are returned.
        """
        if extra is None or "reference_images" not in extra:
            return ResponseDistribution(1 / 3, 1 / 3, 1 / 3, raw={"warning": "no reference images"})

        refs = extra["reference_images"]
        query_feat = self._encode_image(illusion)

        scores: dict[str, float] = {}
        for label in ("correct", "illusory", "other"):
            ref_feat = self._encode_image(refs[label])
            scores[label] = float((query_feat * ref_feat).sum())

        logits = torch.tensor([scores["correct"], scores["illusory"], scores["other"]])
        probs = torch.softmax(logits, dim=0).tolist()

        ctrl_feat = self._encode_image(control)
        ctrl_scores = {
            label: float((ctrl_feat * self._encode_image(refs[label])).sum())
            for label in ("correct", "illusory", "other")
        }

        return ResponseDistribution(
            correct=probs[0],
            illusory=probs[1],
            other=probs[2],
            raw={"scores": scores, "ctrl_scores": ctrl_scores},
        )


# ──────────────────────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────────────────────

_DEFAULT_PROMPTS: dict[str, dict[str, str]] = {
    "geometric": {
        "correct": "The two lines are equal in length.",
        "illusory": "The two lines are different in length.",
        "other": "The image shows two lines.",
    },
    "color": {
        "correct": "The two patches are the same brightness.",
        "illusory": "The two patches are different in brightness.",
        "other": "The image shows two grey patches.",
    },
    "angle": {
        "correct": "The lines are parallel.",
        "illusory": "The lines are not parallel.",
        "other": "The image shows a set of lines.",
    },
    "motion": {
        "correct": "The static pattern appears still.",
        "illusory": "The static pattern appears to move or flicker.",
        "other": "The image shows an abstract pattern.",
    },
    "impossible": {
        "correct": "The object in the image is physically possible.",
        "illusory": "The object in the image is physically impossible.",
        "other": "The image shows an ambiguous object.",
    },
}


def _get_text_prompts(
    extra: dict[str, Any] | None,
    category: str,
    illusion_type: str,
) -> dict[str, str]:
    if extra is not None and "text_prompts" in extra:
        return extra["text_prompts"]
    return _DEFAULT_PROMPTS.get(category, _DEFAULT_PROMPTS["geometric"])
